#!/usr/bin/env python3
"""Generate SUBMISSION_CHECKLIST.md reflecting current readiness.

Mirrors the Participant Guide Section 11 final pre-submit checklist and
records current pass/fail state from the QA report (if present).
"""

from __future__ import annotations
import json
from pathlib import Path

CHECKLIST = [
    ("GET /health is reachable and returns readiness response", "health"),
    ("POST /optimize-energy accepts 1-3 operator notes with exact schema", "schema"),
    (
        "Every operator note produces exactly one directive_interpretation entry in note_index order; no_op uses applies=false + null adjustment, all other directives use applies=true with required shape",
        "schema",
    ),
    (
        "LLM output is deterministically guarded; directive hours unique 0-23 ascending; numerics valid; invalid model output cannot invent constraints",
        "guardrails",
    ),
    (
        "hourly_plan obeys organizer-ground-truth directives + energy balance + effective-solar + battery + rate-limit + grid-cap + end-of-day rules",
        "physics",
    ),
    (
        "total_grid_kwh, total_cost_bdt, peak_grid_kwh match values recalculated from hourly_plan",
        "cost",
    ),
    (
        "README self-contained with quickstart, env vars, model/provider, run/test commands",
        "docs",
    ),
    (
        "Repository created after question reveal, kept private during event, made public after deadline; endpoint remains reachable for evaluation",
        "deploy",
    ),
    (
        "Docker fallback image submitted with pullable tag/digest; documented docker pull/run commands work; /health becomes ready; no secrets baked in",
        "docker",
    ),
    (
        "3-minute video accessible and explains problem, architecture, solution approach, LLM->guardrails->optimizer pipeline, and how to run/test",
        "video",
    ),
]


def main():
    qa = Path("QA_REPORT.md")
    overall = "UNKNOWN"
    if qa.exists():
        text = qa.read_text()
        for line in text.splitlines():
            if line.startswith("**Overall Status:**"):
                overall = line.split("**")[-2].strip()
                break

    lines = ["# GridWise Submission Checklist", ""]
    lines.append(f"_QA Status: **{overall}**_")
    lines.append("")
    for desc, key in CHECKLIST:
        mark = "[x]" if overall == "PASS" else "[ ]"
        lines.append(f"- {mark} {desc}")
    lines.append("")
    lines.append("Generated by scripts/generate_submission_checklist.py")
    Path("SUBMISSION_CHECKLIST.md").write_text("\n".join(lines))
    print("Wrote SUBMISSION_CHECKLIST.md")


if __name__ == "__main__":
    main()
